spring.application.name=demo

# ======================
# MYSQL (DOCKER)
# ======================
spring.datasource.url=jdbc:mysql://localhost:3306/Bank_app
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.signer-key=${JWT_SIGNER_KEY:ffb8c01517a9aeefe2224e8f51fc0ac9edafb00cada04f4ca8afc784e3d49f84}